In [1]:
import pandas as pd
import geopandas as gpd

In [2]:
df_lat = pd.read_csv('entrada/LATLONG.csv', sep=';')

In [3]:
df_lat

             ID      LNG_LOJA      LAT_LOJA     LNG_FRIGO     LAT_FRIGO
0          boi1      -35,3285       -5,7921   -44,1392295   -19,9488162
1          boi3      -35,2099       -5,8455   -61,8057425   -11,7254349
2          boi4      -35,2099       -5,8455  -48,42480679  -7,633314911
3          boi5      -35,2099       -5,8455  -48,42480679  -7,633314911
4          boi6      -35,2294       -5,8851  -54,61574357  -20,45802999
...         ...           ...           ...           ...           ...
2192  frango958    -35,261562     -5,917757  -40,78231328  -20,42575728
2193  frango959    -35,261106     -5,914657  -39,76666667  -17,55277778
2194  frango961    -35,275551     -5,924013  -39,76666667  -17,55277778
2195  frango962  -35,30201418  -5,748905771  -52,03363277   -28,0547569
2196  frango963    -35,264792      -5,92846  -39,76666667  -17,55277778

[2197 rows x 5 columns]

In [4]:
for col in ['LNG_LOJA', 'LAT_LOJA', 'LNG_FRIGO', 'LAT_FRIGO']:
    df_lat[col] = df_lat[col].str.replace(',', '.').astype(float)
df_lat

             ID   LNG_LOJA  LAT_LOJA  LNG_FRIGO  LAT_FRIGO
0          boi1 -35.328500 -5.792100 -44.139229 -19.948816
1          boi3 -35.209900 -5.845500 -61.805743 -11.725435
2          boi4 -35.209900 -5.845500 -48.424807  -7.633315
3          boi5 -35.209900 -5.845500 -48.424807  -7.633315
4          boi6 -35.229400 -5.885100 -54.615744 -20.458030
...         ...        ...       ...        ...        ...
2192  frango958 -35.261562 -5.917757 -40.782313 -20.425757
2193  frango959 -35.261106 -5.914657 -39.766667 -17.552778
2194  frango961 -35.275551 -5.924013 -39.766667 -17.552778
2195  frango962 -35.302014 -5.748906 -52.033633 -28.054757
2196  frango963 -35.264792 -5.928460 -39.766667 -17.552778

[2197 rows x 5 columns]

In [5]:
input_dataframe = df_lat.copy()
lon_column_name = 'LNG_LOJA'
lat_column_name = 'LAT_LOJA'

geo_df_loja = gpd.GeoDataFrame(input_dataframe, geometry=gpd.points_from_xy(input_dataframe[lon_column_name], input_dataframe[lat_column_name]))
geo_df_loja

,ID,LNG_LOJA,LAT_LOJA,LNG_FRIGO,LAT_FRIGO,geometry
0,boi1,-35.328500,-5.792100,-44.139229,-19.948816,POINT (-35.32850 -5.79210)
1,boi3,-35.209900,-5.845500,-61.805743,-11.725435,POINT (-35.20990 -5.84550)
2,boi4,-35.209900,-5.845500,-48.424807,-7.633315,POINT (-35.20990 -5.84550)
3,boi5,-35.209900,-5.845500,-48.424807,-7.633315,POINT (-35.20990 -5.84550)
4,boi6,-35.229400,-5.885100,-54.615744,-20.458030,POINT (-35.22940 -5.88510)
...,...,...,...,...,...,...
2192,frango958,-35.261562,-5.917757,-40.782313,-20.425757,POINT (-35.26156 -5.91776)
2193,frango959,-35.261106,-5.914657,-39.766667,-17.552778,POINT (-35.26111 -5.91466)
2194,frango961,-35.275551,-5.924013,-39.766667,-17.552778,POINT (-35.27555 -5.92401)
2195,frango962,-35.302014,-5.748906,-52.033633,-28.054757,POINT (-35.30201 -5.74891)
2196,frango963,-35.264792,-5.928460,-39.766667,-17.552778,POINT (-35.26479 -5.92846)

In [6]:
input_dataframe = df_lat.copy()
lon_column_name = 'LNG_FRIGO'
lat_column_name = 'LAT_FRIGO'

geo_df_frigo = gpd.GeoDataFrame(input_dataframe, geometry=gpd.points_from_xy(input_dataframe[lon_column_name], input_dataframe[lat_column_name]))
geo_df_frigo

,ID,LNG_LOJA,LAT_LOJA,LNG_FRIGO,LAT_FRIGO,geometry
0,boi1,-35.328500,-5.792100,-44.139229,-19.948816,POINT (-44.13923 -19.94882)
1,boi3,-35.209900,-5.845500,-61.805743,-11.725435,POINT (-61.80574 -11.72543)
2,boi4,-35.209900,-5.845500,-48.424807,-7.633315,POINT (-48.42481 -7.63331)
3,boi5,-35.209900,-5.845500,-48.424807,-7.633315,POINT (-48.42481 -7.63331)
4,boi6,-35.229400,-5.885100,-54.615744,-20.458030,POINT (-54.61574 -20.45803)
...,...,...,...,...,...,...
2192,frango958,-35.261562,-5.917757,-40.782313,-20.425757,POINT (-40.78231 -20.42576)
2193,frango959,-35.261106,-5.914657,-39.766667,-17.552778,POINT (-39.76667 -17.55278)
2194,frango961,-35.275551,-5.924013,-39.766667,-17.552778,POINT (-39.76667 -17.55278)
2195,frango962,-35.302014,-5.748906,-52.033633,-28.054757,POINT (-52.03363 -28.05476)
2196,frango963,-35.264792,-5.928460,-39.766667,-17.552778,POINT (-39.76667 -17.55278)

In [7]:
# https://www.ibge.gov.br/geociencias/organizacao-do-territorio/malhas-territoriais/26565-malhas-de-setores-censitarios-divisoes-intramunicipais.html?=&t=downloads

geo_df = gpd.read_file('entrada/24SEE250GC_SIR.shp')
geo_df

,ID,CD_GEOCODI,TIPO,CD_GEOCODB,NM_BAIRRO,CD_GEOCODS,NM_SUBDIST,CD_GEOCODD,NM_DISTRIT,CD_GEOCODM,NM_MUNICIP,NM_MICRO,NM_MESO,geometry
0,72151,240020805000006,URBANO,None,None,24002080500,None,240020805,AÇU,2400208,AÇU,VALE DO AÇU,OESTE POTIGUAR,"POLYGON ((-36.90843 -5.58145, -36.90834 -5.582..."
1,72152,240020805000007,URBANO,None,None,24002080500,None,240020805,AÇU,2400208,AÇU,VALE DO AÇU,OESTE POTIGUAR,"POLYGON ((-36.90586 -5.58354, -36.90556 -5.585..."
2,72153,240020805000008,URBANO,None,None,24002080500,None,240020805,AÇU,2400208,AÇU,VALE DO AÇU,OESTE POTIGUAR,"POLYGON ((-36.90780 -5.58389, -36.90739 -5.586..."
3,72154,240020805000009,URBANO,None,None,24002080500,None,240020805,AÇU,2400208,AÇU,VALE DO AÇU,OESTE POTIGUAR,"POLYGON ((-36.90939 -5.58418, -36.90933 -5.585..."
4,72155,240020805000010,URBANO,None,None,24002080500,None,240020805,AÇU,2400208,AÇU,VALE DO AÇU,OESTE POTIGUAR,"POLYGON ((-36.91135 -5.58195, -36.91135 -5.581..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4306,76368,241490205000003,URBANO,None,None,24149020500,None,241490205,VIÇOSA,2414902,VIÇOSA,PAU DOS FERROS,OESTE POTIGUAR,"POLYGON ((-37.94698 -5.99497, -37.94689 -5.994..."
4307,76369,241500805000001,URBANO,None,None,24150080500,None,241500805,VILA FLOR,2415008,VILA FLOR,LITORAL SUL,LESTE POTIGUAR,"POLYGON ((-35.07768 -6.31092, -35.07510 -6.311..."
4308,76370,241500805000002,URBANO,None,None,24150080500,None,241500805,VILA FLOR,2415008,VILA FLOR,LITORAL SUL,LESTE POTIGUAR,"POLYGON ((-35.07626 -6.31486, -35.07622 -6.314..."
4309,76371,241500805000003,URBANO,None,None,24150080500,None,241500805,VILA FLOR,2415008,VILA FLOR,LITORAL SUL,LESTE POTIGUAR,"POLYGON ((-35.07847 -6.31204, -35.07810 -6.312..."
4310,76372,241500805000004,RURAL,None,None,24150080500,None,241500805,VILA FLOR,2415008,VILA FLOR,LITORAL SUL,LESTE POTIGUAR,"POLYGON ((-35.08447 -6.33993, -35.11744 -6.333..."

In [8]:
geo_df_frigo.set_crs(geo_df.crs, inplace=True)
geo_df_loja.set_crs(geo_df.crs, inplace=True)

,ID,LNG_LOJA,LAT_LOJA,LNG_FRIGO,LAT_FRIGO,geometry
0,boi1,-35.328500,-5.792100,-44.139229,-19.948816,POINT (-35.32850 -5.79210)
1,boi3,-35.209900,-5.845500,-61.805743,-11.725435,POINT (-35.20990 -5.84550)
2,boi4,-35.209900,-5.845500,-48.424807,-7.633315,POINT (-35.20990 -5.84550)
3,boi5,-35.209900,-5.845500,-48.424807,-7.633315,POINT (-35.20990 -5.84550)
4,boi6,-35.229400,-5.885100,-54.615744,-20.458030,POINT (-35.22940 -5.88510)
...,...,...,...,...,...,...
2192,frango958,-35.261562,-5.917757,-40.782313,-20.425757,POINT (-35.26156 -5.91776)
2193,frango959,-35.261106,-5.914657,-39.766667,-17.552778,POINT (-35.26111 -5.91466)
2194,frango961,-35.275551,-5.924013,-39.766667,-17.552778,POINT (-35.27555 -5.92401)
2195,frango962,-35.302014,-5.748906,-52.033633,-28.054757,POINT (-35.30201 -5.74891)
2196,frango963,-35.264792,-5.928460,-39.766667,-17.552778,POINT (-35.26479 -5.92846)

In [9]:
joined_geo_df_frigo = gpd.sjoin(geo_df_frigo, geo_df,  op='within')
joined_geo_df_loja = gpd.sjoin(geo_df_loja, geo_df, op='within')
joined_geo_df_frigo

/opt/conda/lib/python3.12/site-packages/IPython/core/interactiveshell.py:3517: FutureWarning: The `op` parameter is deprecated and will be removed in a future release. Please use the `predicate` parameter instead.
  if await self.run_code(code, result, async_=asy):
/opt/conda/lib/python3.12/site-packages/IPython/core/interactiveshell.py:3517: FutureWarning: The `op` parameter is deprecated and will be removed in a future release. Please use the `predicate` parameter instead.
  if await self.run_code(code, result, async_=asy):

Empty GeoDataFrame
Columns: [ID_left, LNG_LOJA, LAT_LOJA, LNG_FRIGO, LAT_FRIGO, geometry, index_right, ID_right, CD_GEOCODI, TIPO, CD_GEOCODB, NM_BAIRRO, CD_GEOCODS, NM_SUBDIST, CD_GEOCODD, NM_DISTRIT, CD_GEOCODM, NM_MUNICIP, NM_MICRO, NM_MESO]
Index: []

In [10]:
joined_geo_df_loja

,ID_left,LNG_LOJA,LAT_LOJA,LNG_FRIGO,LAT_FRIGO,geometry,index_right,ID_right,CD_GEOCODI,TIPO,CD_GEOCODB,NM_BAIRRO,CD_GEOCODS,NM_SUBDIST,CD_GEOCODD,NM_DISTRIT,CD_GEOCODM,NM_MUNICIP,NM_MICRO,NM_MESO
0,boi1,-35.328500,-5.792100,-44.139229,-19.948816,POINT (-35.32850 -5.79210),3766,75828,241200505000076,URBANO,None,None,24120050500,None,241200505,SÃO GONÇALO DO AMARANTE,2412005,SÃO GONÇALO DO AMARANTE,MACAÍBA,LESTE POTIGUAR
1,boi3,-35.209900,-5.845500,-61.805743,-11.725435,POINT (-35.20990 -5.84550),2746,74724,240810205070127,URBANO,240810205019,Candelária,24081020507,R.A. SUL,240810205,NATAL,2408102,NATAL,NATAL,LESTE POTIGUAR
2,boi4,-35.209900,-5.845500,-48.424807,-7.633315,POINT (-35.20990 -5.84550),2746,74724,240810205070127,URBANO,240810205019,Candelária,24081020507,R.A. SUL,240810205,NATAL,2408102,NATAL,NATAL,LESTE POTIGUAR
3,boi5,-35.209900,-5.845500,-48.424807,-7.633315,POINT (-35.20990 -5.84550),2746,74724,240810205070127,URBANO,240810205019,Candelária,24081020507,R.A. SUL,240810205,NATAL,2408102,NATAL,NATAL,LESTE POTIGUAR
4,boi6,-35.229400,-5.885100,-54.615744,-20.458030,POINT (-35.22940 -5.88510),1086,73148,240325105000199,URBANO,240325105004,Emaús,24032510500,None,240325105,PARNAMIRIM,2403251,PARNAMIRIM,NATAL,LESTE POTIGUAR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2192,frango958,-35.261562,-5.917757,-40.782313,-20.425757,POINT (-35.26156 -5.91776),914,72963,240325105000003,URBANO,240325105002,Centro,24032510500,None,240325105,PARNAMIRIM,2403251,PARNAMIRIM,NATAL,LESTE POTIGUAR
2193,frango959,-35.261106,-5.914657,-39.766667,-17.552778,POINT (-35.26111 -5.91466),913,72962,240325105000002,URBANO,240325105002,Centro,24032510500,None,240325105,PARNAMIRIM,2403251,PARNAMIRIM,NATAL,LESTE POTIGUAR
2194,frango961,-35.275551,-5.924013,-39.766667,-17.552778,POINT (-35.27555 -5.92401),1049,73111,240325105000162,URBANO,240325105012,Rosa dos Ventos,24032510500,None,240325105,PARNAMIRIM,2403251,PARNAMIRIM,NATAL,LESTE POTIGUAR
2195,frango962,-35.302014,-5.748906,-52.033633,-28.054757,POINT (-35.30201 -5.74891),3741,75803,241200505000051,URBANO,None,None,24120050500,None,241200505,SÃO GONÇALO DO AMARANTE,2412005,SÃO GONÇALO DO AMARANTE,MACAÍBA,LESTE POTIGUAR
2196,frango963,-35.264792,-5.928460,-39.766667,-17.552778,POINT (-35.26479 -5.92846),927,72976,240325105000016,URBANO,240325105003,Cohabinal,24032510500,None,240325105,PARNAMIRIM,2403251,PARNAMIRIM,NATAL,LESTE POTIGUAR

In [11]:
joined_geo_df_loja.columns

Index(['ID_left', 'LNG_LOJA', 'LAT_LOJA', 'LNG_FRIGO', 'LAT_FRIGO', 'geometry',
       'index_right', 'ID_right', 'CD_GEOCODI', 'TIPO', 'CD_GEOCODB',
       'NM_BAIRRO', 'CD_GEOCODS', 'NM_SUBDIST', 'CD_GEOCODD', 'NM_DISTRIT',
       'CD_GEOCODM', 'NM_MUNICIP', 'NM_MICRO', 'NM_MESO'],
      dtype='object')

In [12]:
df_loja = joined_geo_df_loja[['ID_left', 'LNG_LOJA', 'LAT_LOJA', 'index_right', 'ID_right', 'CD_GEOCODI', 'TIPO', 'CD_GEOCODB', 'NM_BAIRRO', 'CD_GEOCODS', 'NM_SUBDIST', 'CD_GEOCODD', 'NM_DISTRIT', 'CD_GEOCODM', 'NM_MUNICIP', 'NM_MICRO', 'NM_MESO']].copy()

df_loja

,ID_left,LNG_LOJA,LAT_LOJA,index_right,ID_right,CD_GEOCODI,TIPO,CD_GEOCODB,NM_BAIRRO,CD_GEOCODS,NM_SUBDIST,CD_GEOCODD,NM_DISTRIT,CD_GEOCODM,NM_MUNICIP,NM_MICRO,NM_MESO
0,boi1,-35.328500,-5.792100,3766,75828,241200505000076,URBANO,None,None,24120050500,None,241200505,SÃO GONÇALO DO AMARANTE,2412005,SÃO GONÇALO DO AMARANTE,MACAÍBA,LESTE POTIGUAR
1,boi3,-35.209900,-5.845500,2746,74724,240810205070127,URBANO,240810205019,Candelária,24081020507,R.A. SUL,240810205,NATAL,2408102,NATAL,NATAL,LESTE POTIGUAR
2,boi4,-35.209900,-5.845500,2746,74724,240810205070127,URBANO,240810205019,Candelária,24081020507,R.A. SUL,240810205,NATAL,2408102,NATAL,NATAL,LESTE POTIGUAR
3,boi5,-35.209900,-5.845500,2746,74724,240810205070127,URBANO,240810205019,Candelária,24081020507,R.A. SUL,240810205,NATAL,2408102,NATAL,NATAL,LESTE POTIGUAR
4,boi6,-35.229400,-5.885100,1086,73148,240325105000199,URBANO,240325105004,Emaús,24032510500,None,240325105,PARNAMIRIM,2403251,PARNAMIRIM,NATAL,LESTE POTIGUAR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2192,frango958,-35.261562,-5.917757,914,72963,240325105000003,URBANO,240325105002,Centro,24032510500,None,240325105,PARNAMIRIM,2403251,PARNAMIRIM,NATAL,LESTE POTIGUAR
2193,frango959,-35.261106,-5.914657,913,72962,240325105000002,URBANO,240325105002,Centro,24032510500,None,240325105,PARNAMIRIM,2403251,PARNAMIRIM,NATAL,LESTE POTIGUAR
2194,frango961,-35.275551,-5.924013,1049,73111,240325105000162,URBANO,240325105012,Rosa dos Ventos,24032510500,None,240325105,PARNAMIRIM,2403251,PARNAMIRIM,NATAL,LESTE POTIGUAR
2195,frango962,-35.302014,-5.748906,3741,75803,241200505000051,URBANO,None,None,24120050500,None,241200505,SÃO GONÇALO DO AMARANTE,2412005,SÃO GONÇALO DO AMARANTE,MACAÍBA,LESTE POTIGUAR
2196,frango963,-35.264792,-5.928460,927,72976,240325105000016,URBANO,240325105003,Cohabinal,24032510500,None,240325105,PARNAMIRIM,2403251,PARNAMIRIM,NATAL,LESTE POTIGUAR

In [14]:
df_renda = pd.read_excel('entrada/rendasetor.xlsx', dtype={'Cod_setor': str})
df_renda['V011'] = df_renda['V011'].str.replace(',', '.').astype(float)
df_renda

            Cod_setor     V011
0     240010905000001   559.63
1     240010905000002   483.19
2     240010905000003   682.83
3     240010905000004   885.82
4     240010905000005  1186.61
...               ...      ...
4284  241490205000003   461.77
4285  241500805000001   535.70
4286  241500805000002   588.63
4287  241500805000003   642.60
4288  241500805000004   775.92

[4289 rows x 2 columns]

In [23]:
df_loja = df_loja.merge(df_renda, left_on='CD_GEOCODI', right_on='Cod_setor', how='left')

In [24]:
df_loja

,ID_left,LNG_LOJA,LAT_LOJA,index_right,ID_right,CD_GEOCODI,TIPO,CD_GEOCODB,NM_BAIRRO,CD_GEOCODS,NM_SUBDIST,CD_GEOCODD,NM_DISTRIT,CD_GEOCODM,NM_MUNICIP,NM_MICRO,NM_MESO,Cod_setor,V011
0,boi1,-35.328500,-5.792100,3766,75828,241200505000076,URBANO,None,None,24120050500,None,241200505,SÃO GONÇALO DO AMARANTE,2412005,SÃO GONÇALO DO AMARANTE,MACAÍBA,LESTE POTIGUAR,241200505000076,1316.76
1,boi3,-35.209900,-5.845500,2746,74724,240810205070127,URBANO,240810205019,Candelária,24081020507,R.A. SUL,240810205,NATAL,2408102,NATAL,NATAL,LESTE POTIGUAR,240810205070127,2754.04
2,boi4,-35.209900,-5.845500,2746,74724,240810205070127,URBANO,240810205019,Candelária,24081020507,R.A. SUL,240810205,NATAL,2408102,NATAL,NATAL,LESTE POTIGUAR,240810205070127,2754.04
3,boi5,-35.209900,-5.845500,2746,74724,240810205070127,URBANO,240810205019,Candelária,24081020507,R.A. SUL,240810205,NATAL,2408102,NATAL,NATAL,LESTE POTIGUAR,240810205070127,2754.04
4,boi6,-35.229400,-5.885100,1086,73148,240325105000199,URBANO,240325105004,Emaús,24032510500,None,240325105,PARNAMIRIM,2403251,PARNAMIRIM,NATAL,LESTE POTIGUAR,240325105000199,1812.69
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2189,frango958,-35.261562,-5.917757,914,72963,240325105000003,URBANO,240325105002,Centro,24032510500,None,240325105,PARNAMIRIM,2403251,PARNAMIRIM,NATAL,LESTE POTIGUAR,240325105000003,1298.69
2190,frango959,-35.261106,-5.914657,913,72962,240325105000002,URBANO,240325105002,Centro,24032510500,None,240325105,PARNAMIRIM,2403251,PARNAMIRIM,NATAL,LESTE POTIGUAR,240325105000002,1445.29
2191,frango961,-35.275551,-5.924013,1049,73111,240325105000162,URBANO,240325105012,Rosa dos Ventos,24032510500,None,240325105,PARNAMIRIM,2403251,PARNAMIRIM,NATAL,LESTE POTIGUAR,240325105000162,1082.30
2192,frango962,-35.302014,-5.748906,3741,75803,241200505000051,URBANO,None,None,24120050500,None,241200505,SÃO GONÇALO DO AMARANTE,2412005,SÃO GONÇALO DO AMARANTE,MACAÍBA,LESTE POTIGUAR,241200505000051,904.23
2193,frango963,-35.264792,-5.928460,927,72976,240325105000016,URBANO,240325105003,Cohabinal,24032510500,None,240325105,PARNAMIRIM,2403251,PARNAMIRIM,NATAL,LESTE POTIGUAR,240325105000016,1793.17

In [25]:
df_loja['CD_GEOCODI'].nunique()
df_loja.to_csv('saida/setores_censitarios_loja.csv', index=False)

# Distâncias

In [27]:
from geopy.distance import geodesic

def vincenty_dist(lat1, lon1, lat2, lon2):
    point1 = (lat1, lon1)
    point2 = (lat2, lon2)
    return geodesic(point1, point2).kilometers

lat1, lon1 = 52.2296756, 21.0122287
lat2, lon2 = 41.8919300, 12.5113300

distance = vincenty_dist(lat1, lon1, lat2, lon2)
print(f"Exemplo distância (Vincenty): {distance} km")

Exemplo distância (Vincenty): 1316.2080833061777 km

In [28]:
df_lat

             ID   LNG_LOJA  LAT_LOJA  LNG_FRIGO  LAT_FRIGO
0          boi1 -35.328500 -5.792100 -44.139229 -19.948816
1          boi3 -35.209900 -5.845500 -61.805743 -11.725435
2          boi4 -35.209900 -5.845500 -48.424807  -7.633315
3          boi5 -35.209900 -5.845500 -48.424807  -7.633315
4          boi6 -35.229400 -5.885100 -54.615744 -20.458030
...         ...        ...       ...        ...        ...
2192  frango958 -35.261562 -5.917757 -40.782313 -20.425757
2193  frango959 -35.261106 -5.914657 -39.766667 -17.552778
2194  frango961 -35.275551 -5.924013 -39.766667 -17.552778
2195  frango962 -35.302014 -5.748906 -52.033633 -28.054757
2196  frango963 -35.264792 -5.928460 -39.766667 -17.552778

[2197 rows x 5 columns]

In [29]:
df_distancias = df_lat.copy()

df_distancias['DISTANCIA_KM'] = df_distancias.apply(lambda row: vincenty_dist(row['LAT_LOJA'], row['LNG_LOJA'], row['LAT_FRIGO'], row['LNG_FRIGO']), axis=1)
df_distancias

             ID   LNG_LOJA  LAT_LOJA  LNG_FRIGO  LAT_FRIGO  DISTANCIA_KM
0          boi1 -35.328500 -5.792100 -44.139229 -19.948816   1833.615125
1          boi3 -35.209900 -5.845500 -61.805743 -11.725435   2995.570405
2          boi4 -35.209900 -5.845500 -48.424807  -7.633315   1474.191415
3          boi5 -35.209900 -5.845500 -48.424807  -7.633315   1474.191415
4          boi6 -35.229400 -5.885100 -54.615744 -20.458030   2643.223627
...         ...        ...       ...        ...        ...           ...
2192  frango958 -35.261562 -5.917757 -40.782313 -20.425757   1712.424223
2193  frango959 -35.261106 -5.914657 -39.766667 -17.552778   1377.612779
2194  frango961 -35.275551 -5.924013 -39.766667 -17.552778   1376.084688
2195  frango962 -35.302014 -5.748906 -52.033633 -28.054757   3036.338329
2196  frango963 -35.264792 -5.928460 -39.766667 -17.552778   1376.039998

[2197 rows x 6 columns]

In [30]:
df_distancias.to_csv('saida/distancias.csv', index=False)